In [2]:
import tensorflow as tf
import numpy as np

##### Tensors are multi-dimensional arrays with a uniform type (dtype).

##### All tensors are immutable like Python numbers and strings


# Tensor Bascis


### Rank of tensors


In [16]:
# Rank 0 tensor (dimension = (None)) || shape= ()
r0ten = tf.constant(5)
r0ten

# Rank 1 tensor (dimension = 1) || shape=(n)
r1ten = tf.constant([1, 2, 3, 4])
r1ten

# Rank 2 tensor (2 dimensional) || shape=(m, n)
r2ten = tf.constant([
    [7, 4], [3, 8],
    [3, 9], [3, 3],
    [7, 1], [8, 2]
])
r2ten

# Rank 3 tensor (3d array) || shape= (l, m, n)
r3ten = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 4], [5, 6]],
    [[7, 7], [9, 1]],
    [[2, 3], [6, 5]]
])
print(r3ten)


tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 4]
  [5 6]]

 [[7 7]
  [9 1]]

 [[2 3]
  [6 5]]], shape=(4, 2, 2), dtype=int32)


### Tensor arthemetic


In [4]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])
# Addition
print(a + b)
print(tf.add(a, b))


# Subtraction
print(a - b)
print(tf.subtract(a, b))

# Multiplication (Element wise)
print(a * b)
print(tf.multiply(a, b))


# Exponentation (element wise)
print(a ** 2)

# Matrix multiplication
print(tf.matmul(a, b))
print(a @ b)


tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


#### Other Tensor functions


In [7]:
ten = tf.constant([
    [5, 2, 3],
    [8, 4, 1]
], dtype=tf.float32)

tf.argmax(ten)
tf.nn.softmax(ten)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[8.4379470e-01, 4.2010065e-02, 1.1419519e-01],
       [9.8113519e-01, 1.7970119e-02, 8.9467951e-04]], dtype=float32)>

### Initializing Tensors

##### **Special Tensors**

In [ ]:
# Method 1 (tf.constant) ==> Already covered

# Method 2 (tf.ones() || tf.zeros() )
tf.ones((3, 3), dtype=tf.float64, name='OnesMatrix').numpy()
tf.ones([4, 5], dtype=tf.float64, name='OnesMatrix').numpy()

tf.zeros((2, 4), dtype=tf.float64).numpy()
tf.zeros([6, 3], dtype=tf.int32).numpy()

# Method 3 (tf.eye() Identity-Matrix)

# Creates a regular identity matrix
tf.eye(5)

# Creates an identity matrix `tf.eye(m, n)` with m rows and n columns.. 
# n can be greater than or less than m
tf.eye(3, 4)

# batch-shape parameter takes a tensor(nd-ary) and outputs a batch of identity matrices
tf.eye(3, 3, batch_shape=[2])
tf.eye(4, batch_shape=[2, 4])


##### **Random tensors**

In [112]:
# Distributions :: Normal|| binomial anything!!
tf.random.normal([2, 2], dtype=tf.float16).numpy()
tf.random.normal([5, 2], mean=3, stddev=5, seed=2, dtype=tf.float16).numpy()

# Possion distribution parameters
# lam -> value to distribute new numbers around
x = tf.random.poisson([2,2], [10, 20], seed= 1, dtype=tf.int32).numpy()
tf.random.poisson([3, 3], [12, 32 ,15],seed= 2.5, dtype=tf.int32).numpy()

tf.random.uniform([3, 3], 10, 20, dtype=tf.int32).numpy()
tf.random.uniform([3, 3], 10, 20, dtype=tf.int32).numpy()

tf.linspace(10, 20, 11).numpy()
tf.linspace([0,0], [10,-10], 11)

tf.range(start= 20, limit= 36, delta= 3)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([20, 23, 26, 29, 32, 35])>

### Indexing tensors

In [137]:
# Basic indexing
x = tf.random.uniform([3,3],minval=10, maxval=20, dtype= tf.int32)
print(x)

print()
print(x[0].numpy())
print(x[1].numpy())


print("\nIndividual values")
print(x[2][-1].numpy())

tf.Tensor(
[[11 14 17]
 [12 10 16]
 [15 16 19]], shape=(3, 3), dtype=int32)

[11 14 17]
[12 10 16]

Individual values
19


##### **Slicing along axis** 

In [247]:
x = tf.linspace([12, 43, -32], [-21, 0, -77], 5)
x = tf.cast(x, dtype= tf.int32)
print(x)

print(x.shape)

# Printing entire tensor
x[:].numpy()

# Printing tensor upto index 3
x[:3].numpy()

# Printing first element of all rows
x[:, 0].numpy()



tf.Tensor(
[[ 12  43 -32]
 [  3  32 -43]
 [ -4  21 -54]
 [-12  10 -65]
 [-21   0 -77]], shape=(5, 3), dtype=int32)
(5, 3)


array([ 12,   3,  -4, -12, -21])

In [210]:
#################################################
############ Playing with Tensors ###############
#################################################

t1 = tf.random.poisson([6, 8], 5, dtype=tf.int32)
t1.numpy()

t2 = tf.random.normal([8, 7], mean= 5, stddev= 15, dtype=tf.float32)
t2 = tf.cast(t2, tf.int32)
t2.numpy()

t = t1 @ t2
t.numpy()


t1_slice = t1[0:-1, 3:].numpy()
t_slice = t[-5:, 2:]

# -1 reverses the matrix rows
t3 = t_slice[:: -1, :: -1] * t1_slice
print(t3.shape)
print(tf.gather(t3, [2,1]).numpy()[:, 1:-1:2])


(5, 5)
(5, 5)
[[2455 3545]
 [1175 2220]]


##### **Reshape**

In [230]:
t = tf.random.uniform([5,4], minval= -32, maxval=32, dtype=tf.int32)
print(t)

tf.reshape(t, [10, 2])
tf.reshape(t, [2, -1])

# tf.reshape(t, [7, 3]) || This isn't possible

tf.Tensor(
[[  0  23 -29 -29]
 [ 18 -30  12  19]
 [ 26  -2  -6 -16]
 [-32  16  27   4]
 [-30 -12  25  26]], shape=(5, 4), dtype=int32)


<tf.Tensor: shape=(2, 10), dtype=int32, numpy=
array([[  0,  23, -29, -29,  18, -30,  12,  19,  26,  -2],
       [ -6, -16, -32,  16,  27,   4, -30, -12,  25,  26]])>

##### **Ragged Tensor**

In [242]:
rt = [  [3,4,5,6,0], [6,5,3], [2,4,7,6,9,8], [3,4,90], [0]  ]
rt = tf.ragged.constant(rt)

print(rt.shape)

(5, None)


##### **String tensors**

In [248]:
strten = tf.constant([
    "Gray wolf", "Quick brown fox", "Lazy dog"
])

print(tf.strings.split(strten, sep=" "))


<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>


In [12]:
st = tf.sparse.SparseTensor(
                    indices= [[2,2], [3,3]],
                    values=  [1,2],
                    dense_shape= [4,4]
)
print(st)

st = tf.sparse.to_dense(st)
print('\nDense\n', st)

SparseTensor(indices=tf.Tensor(
[[2 2]
 [3 3]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

Dense
 tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 2]], shape=(4, 4), dtype=int32)
