In [24]:
import tensorflow as tf

In [25]:
# To see where variables are placed
# tf.debugging.set_log_device_placement(False)


In [26]:
t = tf.constant(
    [[52,30,85,34],
    [72,38,92,90],
    [89,80,5,26],
    [20,95,27,52]])
    

x = tf.Variable(t)
x.numpy()

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


array([[52, 30, 85, 34],
       [72, 38, 92, 90],
       [89, 80,  5, 26],
       [20, 95, 27, 52]])

### **Basic Concepts**

In [27]:
# Dtypes
bvar = tf.Variable([False, True, True, False])
tf.argmax(bvar)

# Shapes and Dimensions
bvar.shape
tf.cast(bvar, tf.int16)
tf.reshape(bvar, [2, -1])



Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ArgMax in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Cast in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Reshape in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False,  True],
       [ True, False]])>

### **Placing Varibales and Tensors**

In [ ]:
with tf.device('CPU:0'):
    x = tf.range(0, 11, 2, dtype=tf.int32)
    y = tf.linspace(10, 20, 6)
    y = tf.cast(y, tf.int32)
x.numpy(), y.numpy()

with tf.device('CPU:0'):
    print(x * y)