In [ ]:
'''
    In this guide, we'll learn 
        1. how TensorFlow allows you to make simple changes to your code to get graphs, 
        2. how graphs are stored and represented, 
        3. and how you can use them to accelerate your models.      
'''

#### **TF.function**
> * **`tf.function`: allows us to switch from eager-function to graph function**
> * **`EagerExecution`: TensorFlow operations are executed by Python, operation by operation, and returning results back to Python**
> * **`GraphExecution:` Graph execution means that tensor computations are executed as a TensorFlow graph**

#### **TF.graph**
> * **Graphs are data structures that contain a set of `tf.Operation` objects, which represent units of computation and `tf.Tensor` objects, which represent the units of data that flow between operations.**
> * **Graphs increases Model `portability` outside of Python and increases `performance`.**
> * **Portability: environments without Python interpreter, eg mobile apps, embedded devices, and backend servers**
> * **TensorFlow uses graphs as the `format for saved models` when it exports them from Python.**

##### **`Graph Optimization`:**
> * **`Constant Folding`: Statically infer the value of tensors by folding constant nodes in computation.**
> * **Separate sub-parts of a computation that are independent and split them between `threads or devices`.**
> * **Simplify arithmetic operations by eliminating common sub-expressions.**

**There is an entire optimization system, `Grappler`, to perform this and other speedups.**

### **Setup**

In [3]:
import tensorflow as tf
import timeit as tit
from datetime import datetime

### **Taking advantage of Graphs**

In [33]:
# Defining a regular python function
def func(x, y, b):
    ten = tf.matmul(x, y)
    ten = ten + b
    return ten

# convert regular function to tf.graph
graph_fn = tf.function(func)


# Creating test tensors
t1 = tf.constant([[1., 4., 5.5]]) # 1 x 3
t2 = tf.random.uniform(shape=(3, 2), minval=10, maxval=50, dtype=tf.float32, seed=25) # 3 x 3
t3 = tf.random.normal(shape=(1,2)) # 1 x 3 
print('Printing Tensor T1\n', t1.numpy())
print()
print('Printing Tensor T2\n', t2.numpy())
print()
print('Printing Tensor T3\n', t3.numpy())
print()

regular_fn_result = func(t1,t2,t3)
print('Result of Python function: ', regular_fn_result.numpy(), '\n')

graph_fn_result = graph_fn(t1, t2, t3)
print('Result of TF.Graph function: ', graph_fn_result.numpy(), '\n')

# Checking equility of the results
try:
    assert(regular_fn_result == graph_fn_result)
except:
    print('The function failed')


Printing Tensor T1
 [[1.  4.  5.5]]

Printing Tensor T2
 [[13.645496 47.51658 ]
 [25.756025 41.96839 ]
 [29.448595 17.214098]]

Printing Tensor T3
 [[-2.6894324  -0.33422378]]

Result of Python function:  [[275.94745 309.73346]] 

Result of TF.Graph function:  [[275.94745 309.73346]] 

The function failed


In [40]:

def inner_fn(t1,t2,t3):
    ten = tf.matmul(t1,t2)
    ten = ten * t3
    return ten
# Using @tf.function directly to create graphs
@tf.function
def outr_fn(x):
    t1 = tf.constant([[3.],[6.]])
    t2 = tf.constant(4.5)

    # tf.function applies to a function and all other functions it calls
    return inner_fn(x, t1, t2)
        
# Calling the tf function
t1 = tf.ones(shape=(1, 2))
print(outr_fn(t1))


tf.Tensor([[40.5]], shape=(1, 1), dtype=float32)


* ##### **Python funtions to graphs**

* ##### **Polymorphism: One funtion, many graphs**

### **Using TF.function**

* ##### **Graph Exec vs Eager Exec**

* ##### **Non-strict Execution**

* ##### **Best practices** 

### **Optimization benchmarks**

* ##### **Performance**